source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
target "ben_son" do

pod 'Kingfisher', '~> 4.9.0'
pod 'YYText', '~> 1.0.7'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'YYCache', '~> 1.0.4'
pod 'FLAnimatedImage', '~> 1.0.12'
pod 'Moya/RxSwift'
pod 'ObjectMapper', '~> 3.3.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'FSPagerView', '~> 0.8.1'
#pod 'IQKeyboardManagerSwift', '~> 6.1.1'
pod 'TPKeyboardAvoiding', '~> 1.3.2'
pod 'MBProgressHUD', '~> 1.1.0'
#pod 'ZFPlayer/AVPlayer', '3.0'

pod 'RxSwift', '~> 4.3.0'
pod 'RxCocoa', '~> 4.3.0'
pod 'RxDataSources', '~> 3.1.0'
 
pod 'SKPhotoBrowser', '~> 6.0.0'
pod 'LTMorphingLabel', '~> 0.5.8'
#pod 'FSCalendar', '~> 2.7.9'

pod 'UMCCommon'
pod 'UMCCommonLog' #可在发布 App 前移除
pod 'UMCAnalytics' #统计
pod 'JPush', '~> 3.1.0'
pod 'UMCShare/Social/ReducedWeChat' #微信
pod 'UMCShare/Social/Email'
pod 'UMCShare/Social/ReducedQQ' #QQ
pod 'UMCShare/Social/ReducedSina'  #新浪


pod 'WechatOpenSDK', '~> 1.8.2'
pod 'AlipaySDK-iOS', '~> 15.5.5'
end
